# -*- coding: utf-8 -*-
"""Task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11KXh3K4YX8pTZtQXC9UXnv49tyeRqNOx

Create a 1000 x 1000 random numpy array
Measure how long the creation takes
Convert the array into bytes
Recreate the array from the bytes

References:
time package
numpy package
np.frombuffer
"""

import time
import numpy as np

start_time =time.time()
random_array =np.random.rand(1000,1000)
print(f"Created array{random_array}")
end_time =time.time()
creation_time = end_time - start_time
print(f"Array creation time: {creation_time} seconds")
array_bytes = random_array.tobytes()
recreated_array =np.frombuffer(array_bytes,dtype=random_array.dtype).reshape(random_array.shape)
print(f"Recreaeted array :{recreated_array}")