# -*- coding: utf-8 -*-
"""Task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11KXh3K4YX8pTZtQXC9UXnv49tyeRqNOx
"""

var_1 = 10
var_2 = "Hi"